name: uas_ambw
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  intl: ^0.19.0
  pinput: ^5.0.0
  hive: ^2.2.3
  hive_flutter: 

  crypt: ^4.3.1
  uuid: ^4.4.0
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true
